### ISSUE TITLE
Support PostgreSQL's own connection URI format

### ISSUE THREAD

**Issue by simeonvandersteen** [bbcarchdev/libsql#1]
The URI schemes `postgres` and `postgresql` should be supported in addition to the libsql-defined `pgsql` (https://github.com/bbcarchdev/libsql/blob/develop/engine.c#L55)

See http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING.

**Comment by nevali** [comment]
Note that this code was implemented some time before PostgreSQL defined its own connection string URIs, which were defined as of PostgreSQL 9.2.

**Comment by simeonvandersteen** [comment]
Ah right, well, just to avoid confusion that's all :)
